export type Role='SYSTEM_ADMINISTRATOR'|'CENTRAL_STORE_MANAGER'|'SITE_STORE_MANAGER'|'PROCUREMENT_OFFICER'|'FINANCE'|'EXECUTIVE_MANAGEMENT';
export function canAccessAdmin(role:Role){return role==='SYSTEM_ADMINISTRATOR';}
